#define MAIN_SDL_WINDOW_TITLE "JXO Application"

#define INITIAL_SDL_WINDOW_X_POS 0 
#define INITIAL_SDL_WINDOW_Y_POS 0 
#define INITIAL_SDL_WINDOW_WIDTH 1280 
#define INITIAL_SDL_WINDOW_HEIGHT 720

#define GOOD_EXIT 0
#define BAD_EXIT 1